# Generated by Django 4.2.11 on 2024-05-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='po',
            name='po_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
