# Generated by Django 4.2.11 on 2024-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_po_po_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloatValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='po',
            old_name='deliver_date',
            new_name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='histperformance',
            name='average_response_time',
        ),
        migrations.RemoveField(
            model_name='histperformance',
            name='on_time_delivery_rate',
        ),
        migrations.RemoveField(
            model_name='histperformance',
            name='quality_rating_avg',
        ),
        migrations.AddField(
            model_name='histperformance',
            name='average_response_time',
            field=models.ManyToManyField(related_name='art_fl', to='api.floatvalue'),
        ),
        migrations.AddField(
            model_name='histperformance',
            name='on_time_delivery_rate',
            field=models.ManyToManyField(related_name='otd_fl', to='api.floatvalue'),
        ),
        migrations.AddField(
            model_name='histperformance',
            name='quality_rating_avg',
            field=models.ManyToManyField(related_name='qra_fl', to='api.floatvalue'),
        ),
    ]
